# Generated by Django 4.0.3 on 2022-04-06 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_mod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('detailid', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
