# Generated by Django 4.0.3 on 2022-04-08 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_mod', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='companyinstitution',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='clientproject',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=30)),
                ('detailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mod.userdetails')),
            ],
        ),
    ]
